In [8]:
from fasthtml.common import *
from fasthtml.jupyter import JupyUvi, HTMX
from dataclasses import dataclass
from datetime import datetime
from math import ceil
import pandas as pd

db = database('trfc.db')

app, rt = fast_app(pico=True)

In [32]:
def get_plr_game_goals(season):

    params = [season]

    query = f"""
        SELECT 
            p.surname || ', ' || p.forename as player,
            r.game_no,
            COUNT(g.player_id) as goals_scored,
            COUNT(yc.player_id) as yellow_cards,
            COUNT(rc.player_id) as red_cards
        FROM results r
        LEFT JOIN player_apps pa ON r.game_date = pa.game_date
        LEFT JOIN players p ON pa.player_id = p.player_id
        LEFT JOIN goals g ON r.game_date = g.game_date AND pa.player_id = g.player_id
        LEFT JOIN cards_yellow yc ON r.game_date = yc.game_date AND pa.player_id = yc.player_id
        LEFT JOIN cards_red rc ON r.game_date = rc.game_date AND pa.player_id = rc.player_id
        WHERE r.season = ?
        GROUP BY player, r.game_no
        ORDER BY player, game_no
    """

    cursor = db.conn.execute(query, params)
    columns = [description[0] for description in cursor.description]
    return [dict(zip(columns, record)) for record in cursor.fetchall()]

app, rt = fast_app()

df = get_plr_game_goals('2024/25')

df = pd.DataFrame(df)

pivot_table = df.pivot(
    index='player',
    columns='game_no',
    values='goals_scored'
).fillna('')

header_cells = [Th("Player")]
header_cells.extend(
    Th(f"Game {col}") 
    for col in pivot_table.columns
)
header = Tr(header_cells)

rows = []
for player in pivot_table.index:
    cells = [Td(player)]
    cells.extend(
        Td(str(val)) 
        for val in pivot_table.loc[player]
    )
    rows.append(Tr(cells))

table = Table(
    Thead(header),
    Tbody(rows)
)

@rt("/")

def get():
    return Titled("Soccer Goals Table",
            P("Goals scored by player and game"),
            Div(table)
        )

In [33]:
df

            player  game_no  goals_scored  yellow_cards  red_cards
0    Bradshaw, Zak        1             0             0          0
1    Bradshaw, Zak        2             0             0          0
2    Bradshaw, Zak        3             0             0          0
3    Bradshaw, Zak        4             0             0          0
4    Bradshaw, Zak        6             0             0          0
..             ...      ...           ...           ...        ...
394   Wood, Connor       23             0             0          0
395   Wood, Connor       24             0             0          0
396   Wood, Connor       25             0             0          0
397   Wood, Connor       26             0             0          0
398   Wood, Connor       27             0             1          0

[399 rows x 5 columns]

In [36]:
pivot_table.reset_index()

game_no,player,1,2,3,4,5,6,7,8,9,...,18,19,20,21,22,23,24,25,26,27
0,"Bradshaw, Zak",0.0,0.0,0.0,0.0,,0.0,0.0,0.0,0.0,...,,,0.0,,0.0,,0.0,0.0,,
1,"Davies, Tom",0.0,,0.0,0.0,0.0,0.0,0.0,0.0,,...,0.0,0.0,0.0,0.0,0.0,,,,0.0,0.0
2,"Davison, Josh",0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,,...,,0.0,0.0,,0.0,,,0.0,,0.0
3,"Dennis, Kristian",,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,...,0.0,,1.0,0.0,0.0,0.0,,1.0,1.0,0.0
4,"Drysdale, Declan",,,,,,,,,,...,,,0.0,,,0.0,0.0,0.0,,0.0
5,"Finley, Sam",,,,,,,,,,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,"Hawkes, Josh",,,,,,,,,,...,0.0,0.0,1.0,0.0,0.0,0.0,,,,0.0
7,"Hendry, Regan",0.0,0.0,0.0,,0.0,,,0.0,0.0,...,0.0,0.0,,,,,,,,
8,"Jennings, Connor",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9,"Khan, Saidou",,,,,,,,0.0,0.0,...,,,,,,,,,,
10,"McGee, Luke",0.0,,0.0,,0.0,,0.0,0.0,0.0,...,0.0,0.0,,0.0,0.0,0.0,0.0,,0.0,0.0
11,"Merrie, Chris",,0.0,,0.0,,0.0,0.0,,0.0,...,,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,"Morris, Kieron",0.0,,,,,,,0.0,,...,0.0,1.0,,0.0,,0.0,0.0,0.0,0.0,
13,"Murphy, Joe",,0.0,,0.0,,0.0,,,,...,,,0.0,,,,,0.0,,
14,"Norman, Cameron",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,,0.0
15,"Norris, Luke",0.0,0.0,0.0,,,,,0.0,0.0,...,0.0,0.0,,0.0,,,,,,
16,"O'Connor, Lee",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,,0.0,0.0,0.0,,,0.0,0.0,0.0,0.0
17,"Patrick, Omari",0.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,...,0.0,0.0,,0.0,0.0,0.0,0.0,1.0,1.0,0.0
18,"Saunders, Harvey",0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,"Solomon, Sol",,0.0,,0.0,0.0,0.0,,,0.0,...,,,0.0,,,,0.0,0.0,,1.0
20,"Taylor, Samuel",,,,,,,,,,...,,,0.0,,0.0,,0.0,0.0,,
21,"Turnbull, Jordan",,,,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
22,"Walker, Brad",0.0,0.0,0.0,0.0,0.0,0.0,,,,...,,,,,,,,,,
23,"Williams, Josh",,1.0,,0.0,,0.0,,,0.0,...,,,,,,,,,,
24,"Wood, Connor",0.0,0.0,0.0,0.0,,0.0,0.0,0.0,0.0,...,0.0,0.0,,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
# server = JupyUvi(app)

In [17]:
HTMX()

In [7]:
server.stop()